# -*- coding: utf-8 -*-
"""Mains.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16SSWvBslqI0Ae6Iz_Kaetj03TyDOzLVn
"""

import csv   
   
# csv file id: student_recs.csv 
filename="student_recs.csv"
filePath="D:\UNH\Fall 2020\Python\Term Project\"  # modify for your file system.
student_recs = []
# open the file using "with" statement: 
with open(filePath + filename,'r') as data: 
    for rec in csv.reader(data):
        student_name,student_ID,student_admit_year,student_course_list = rec
        student_course_list = student_course_list.replace('_', ', ')
        student_recs.append((student_name, student_ID, student_admit_year, student_course_list))

"""# New Section"""

for i in range(len(student_recs)):
    print(student_recs[i])

import csv   
   
# csv file id: student_recs.csv 
filename="course_list.csv"
filePath="D:\UNH\Fall 2020\Python\Term Project\"  # modify for your file system.
course_list = []
# open the file using "with" statement: 
with open(filePath + filename,'r') as data: 
    for course in csv.reader(data):
        course_list.append(tuple(course))

for i in range(len(course_list)):
    print(course_list[i])



for i in range(1, len(student_recs)):
    txt = "Name: {0}, {1:<12s}  ID: {2:<12s}  Year: {3}".format(student_recs[i][0].split(' ')[1], student_recs[i][0].split(' ')[0], student_recs[i][1], student_recs[i][2])
    print(txt)
    print("CourseID       Credits       Description")
    courses = student_recs[i][3].split(',')
    courses = [string.strip() for string in courses]
    total_hours = 0
    for k in range(0, len(courses)):
        for j in range(0, len(course_list)):
            if courses[k] in course_list[j]:
                credits = course_list[j][2]
                course_description = course_list[j][3]
                course_id = courses[k]
                print(course_id, "       ", credits, "       ", course_description)
                total_hours = total_hours + int(credits)
    print("\n")
    print("Total Hours: ", total_hours)
    print("\n")
    print("\n")
    print("\n")

for i in range(1, len(course_list)):
    txt = "Course: {0:<4s}{1}     Credits: {2}".format(course_list[i][1], course_list[i][3], course_list[i][2])
    print(txt)
    print("Student Name            ID")
    num = 0
    for k in range(len(student_recs)):
        courses = student_recs[k][3].split(',')
        courses = [string.strip() for string in courses]  
        #print(courses)
        if course_list[i][1] in courses:
            last_name = student_recs[k][0].split(' ')[1]
            first_name = student_recs[k][0].split(' ')[0]
            id = student_recs[k][1]
            num = num + 1
            print(last_name, ", ", first_name, "       ", id)
    print("Total# Students: ", num)
    print("\n")
    print("\n")